language: java
jdk:
  - openjdk8

#travis ci를 어느 브랜치가 푸시될 때 수행할지 지정
#현재옵션 : 오직 master 브랜치에 push될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 홈, 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
#master 브랜치에 푸시되었을때 수행하는 명령어, 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행
script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice-re *
  - mkdir -p deployRe
  - mv springboot-webservice-re.zip deployRe/springboot-webservice-re.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #travis repo 셋팅 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: hac0102-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deployRe   #brfore_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hac0102-springboot-build
    key: springboot-webservice-re.zip
    bundle_type: zip
    application: springboot-webservice-re
    deployment_group: springboot-webservice-re-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hac0102@naver.com